SSP.go
=> bug solved to support int search

SSP.go
=> Added bool filtering

SSP.go, go.mod
=> coment added

SSP.go
=> Case sensitive option

SSP.go
=> changed: case sensitive false by default

SSP.go, SSP_test.go
=> bug on int global fielsd solved

SSP.go, SSP_test.go
=> regular expression added

README.md, SSP.go, SSP_test.go, go.mod
=> global regex fixed

SSP.go
Need to be tested.
Read UUID type ans send it as string
=> Read UUID as string

SSP.go, test.go, test/models/user.go
=> varchar enabled

SSP.go, SSP_test.go, test.go
=> Managing errors

SSP.go, functions_test.go, test/models/user.go
=> INT8 compatibility

SSP.go
=> better error description

SSP.go
=> int 8 bug for sqlite fixed

.gitignore, SSP.go, functions_test.go, test/models/user.go
=> Column with reserver word as name works

SSP.go, functions_test.go, test/dbs/global.go, test/models/pets.go, test/models/user.go
=> Join compatibility

functions_test.go, go.mod, go.sum
=> V2 module changed

SSP.go, functions_test.go, test/models/user.go
=> pass BYTEA fields

SSP.go
=> more secure

SSP.go
=> Order with nulls and test refactor

SSP.go, functions_test.go, test/models/pets.go, test/models/user.go
=> refactor order

SSP.go
=> better check sqlite

SSP.go, functions_test.go, test/models/user.go
=> admit spaces

README.md, SSP.go
=> Custom search function
